parameters:
#    davidtodos.example.class: david\todosBundle\Example

services:
#    davidtodos.example:
#        class: %davidtodos.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
